<a href="https://colab.research.google.com/github/blaewood/Python_AI_Programming/blob/main/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8_3_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#필기 숫자 인식 - 훈련 집합으로 학습하고 테스트 집합으로 성능 측정
from sklearn import datasets
from sklearn import svm
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
digit=datasets.load_digits()
x_train,x_test,y_train,y_test=train_test_split(digit.data,digit.target, train_size=0.6)


In [8]:
s=svm.SVC(gamma=0.001)
s.fit(x_train, y_train)

SVC(gamma=0.001)

In [9]:
res=s.predict(x_test)

In [10]:
conf=np.zeros((10,10))
for i in range(len(res)):
  conf[res[i]][y_test[i]]+=1
print(conf)

[[71.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 68.  0.  0.  0.  0.  0.  0.  2.  0.]
 [ 0.  0. 60.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 63.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 86.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0. 71.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0. 74.  0.  0.  0.]
 [ 0.  0.  0.  1.  1.  0.  0. 74.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 81.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  1.  1. 61.]]


In [11]:
no_correct=0
for i in range(10):
  no_correct+=conf[i][i]
accuracy=no_correct/len(res)
print("테스트ㅡ 집합에 대한 정확률은", accuracy*100,"%입니다.")

테스트ㅡ 집합에 대한 정확률은 98.60917941585535 %입니다.
